services:
  db:
    image: mysql:latest
    restart: always
    container_name: django_db
    ports:
      - "3306:3306"
    # volumes:
    #   - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: data
