# Generated by Django 5.0.6 on 2024-07-04 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineitem',
            name='customer',
        ),
        migrations.AddField(
            model_name='lineitem',
            name='invoice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='factures.invoice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='message',
            field=models.TextField(default='this is a default message.'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='service',
            field=models.TextField(),
        ),
    ]
