# Generated by Django 5.0.7 on 2024-07-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0003_alter_invoice_customer_alter_invoice_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=20.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='customer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='message',
            field=models.TextField(blank=True, default='This is a default message.'),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='lineitem',
            name='service',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
