# Generated by Django 5.0.7 on 2024-07-23 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0005_invoice_subtotal_invoice_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='tax',
        ),
    ]
