# Generated by Django 5.0.7 on 2024-07-29 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('factures', '0006_remove_invoice_subtotal_remove_invoice_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='unique_id',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
    ]
